# Generated by Django 4.0.3 on 2022-06-05 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpositionchange',
            options={'ordering': ['job_position', 'date_from'], 'verbose_name': 'История смены должностей сотрудниками', 'verbose_name_plural': 'История смены должностей сотрудниками'},
        ),
        migrations.AlterField(
            model_name='jobpositionchange',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jobpositionchange',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherdocument',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='staff.teacher'),
        ),
    ]
