# Generated by Django 4.0.3 on 2022-06-19 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_classroom_owner_alter_lesson_teacher_classroomklass'),
        ('staff', '0003_alter_jobpositionchange_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('lesson_type', models.CharField(max_length=255)),
                ('lesson_plan', models.TextField(blank=True, null=True)),
                ('lesson_flow', models.TextField(blank=True, null=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_plans', to='school.lesson')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='staff.teacher')),
            ],
            options={
                'verbose_name': 'План урока',
                'verbose_name_plural': 'Планы уроков',
            },
        ),
    ]
