# Generated by Django 4.0.3 on 2022-06-19 11:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_lessonplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='lesson_flow',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='lesson_plan',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='purpose',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
