# Generated by Django 4.0.3 on 2022-06-12 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_classroomteacher_klass_and_more'),
        ('student', '0002_alter_studentdocument_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentklass',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='school.klass'),
        )
    ]
