# Generated by Django 4.0.3 on 2022-06-12 11:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_studentklass_klass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreview',
            name='characteristic',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
