# Generated by Django 4.0.3 on 2022-06-12 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_jobpositionchange_options_and_more'),
        ('student', '0004_alter_studentreview_characteristic'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreview',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.teacher'),
        ),
    ]
